TinderForPets.WebMVC/Controllers/DogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TinderForPets.Models.Dog;
using TinderForPets.Services;

namespace TinderForPets.WebMVC.Controllers
{
    [Authorize]
    public class DogController : Controller
    {
        // GET: Dog
        public ActionResult Index()
        {
            var service = CreateDogService();
            var model = service.GetDogs();
            return View(model);
        }

        public ActionResult User()
        {
            var service = CreateDogService();
            var model = service.GetDogs();
            return View(model);
        }

        private DogService CreateDogService()
        {
            //var userId = Guid.Parse(User.Identity.GetDogId());
            var service = new DogService();
            return service;
        }

        // GET: Dog/Details/5
        public ActionResult Details(int id)
        {
            var svc = CreateDogService();
            var model = svc.GetDogById(id);

            return View(model);
        }

        // GET: Dog/UserDetails/5
        public ActionResult UserDetail(int id)
        {
            var svc = CreateDogService();
            var model = svc.GetDogById(id);

            return View(model);
        }

        // GET: Dog/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dog/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DogCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateDogService();

            if (service.CreateDog(model))
            {
                TempData["SaveResult"] = "Your Pet was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Pet could not be created.");

            return View(model);
        }

        // GET: Dog/Edit/5
        public ActionResult Edit(int id)
        {
            var service = CreateDogService();
            var detail = service.GetDogById(id);
            var model =
                new DogEdit
                {
                    PetId = detail.PetId,
                    Name = detail.Name,
                    Breed = detail.Breed,
                    HairType = detail.HairType,
                    Age = detail.Age,
                    ShelterId = detail.ShelterId
                };
            return View(model);
        }

        // POST: Dog/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, DogEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.PetId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);

            }

            var service = CreateDogService();

            if (service.UpdateDog(model))
            {
                TempData["SaveResult"] = "Your Pet was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Pet could not be updated.");
            return View(model);
        }

        // GET: Dog/Delete/5
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateDogService();
            var model = svc.GetDogById(id);

            return View(model);
        }

        // POST: Dog/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteDog(int id)
        {
            var service = CreateDogService();

            service.DeleteDog(id);

            TempData["SaveResult"] = "Your Pet was deleted";

            return RedirectToAction("Index");
        }
    }
}

TinderForPets.WebMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TinderForPets.WebMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TinderForPets.WebMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>I, Mark Suverkrup, indroduce to you, TinderForPets.  This revolutionary service seeks to connect orphaned pets with a loving and supportive home.
    By allowing Animal Shelter Owners to post and advertise pets that have nowhere else to go, prospecive owners are able to easily find these pets
    and find a way to adopt them.</p>

TinderForPets.WebMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Pet Way<br />
    Barkeyville, PA 98052<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Email:</strong>   <a href="mailto:marksuverkrup@gmail.com">tinderforpets@tfp.com</a><br />
    <strong>Humane Society:</strong> <a href="https://www.humanesociety.org/resources/adopting-animal-shelter-or-rescue-group">Partner with us.</a>
</address>

TinderForPets.WebMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>TinderForPets</h1>
    <p class="lead">Find your next furry friend.  We've been connecting Animal Shelters with people looking to adopt since 2021.</p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
    <p>
        @Html.ActionLink("View Pets", "User", "Dog")
    </p>
</div>

<div class="row light">
    <div class="col-md-4">
        <h2>Where to Start</h2>
        <p>
            If you are looking for a good place to find more information about adopting an animal and the implications that can go along with it, I urge you to visit The Humane Society
            for more information or to donate.
        </p>
        <p><a class="btn btn-default" href="https://www.humanesociety.org/resources/adopting-animal-shelter-or-rescue-group">Humane Society &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Refine Your Search</h2>
        <p>If you are looking for a more precise way to find your new pet, we have partered with PetFinder, check them out!</p>
        <p><a class="btn btn-default" href="https://www.petfinder.com/">PetFinder &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Facebook</h2>
        <p>If you are looking to get involved but don't really know how, we suggest you look into our social media to find event you can parter with to further the cause.</p>
        <p><a class="btn btn-default" href="https://www.facebook.com/groups/1653154088263047">Facebook &raquo;</a></p>
    </div>
</div>